export type ChainListInfo = {
  name: string;
  chain: string;
  rpc: string[];
  shortName: string;
  chainId: number;
  networkId: number;
  icon: any;
};
export const chainList: ChainListInfo[] = [
  {
    name: 'Ethereum',
    chain: 'ETH',
    rpc: ['https://eth-mainnet.g.alchemy.com/v2/YAlZobalfJSKjWMz3UvAFd9iRfvIuB6I'],
    shortName: 'eth',
    chainId: 1,
    networkId: 1,
    icon: require('../../assets/chain/eth.png'),
  },
  {
    name: 'Arbitrum One',
    chainId: 42161,
    shortName: 'arb1',
    chain: 'ETH',
    networkId: 42161,
    rpc: ['https://arb1.arbitrum.io/rpc', 'https://arbitrum-one.publicnode.com', 'wss://arbitrum-one.publicnode.com'],
    icon: require('../../assets/chain/arb.png'),
  },
  {
    name: 'Arbitrum Nova',
    chainId: 42170,
    shortName: 'arb-nova',
    chain: 'ETH',
    networkId: 42170,
    rpc: ['https://nova.arbitrum.io/rpc', 'https://arbitrum-nova.publicnode.com', 'wss://arbitrum-nova.publicnode.com'],
    icon: require('../../assets/chain/arb_nova.png'),
  },
  {
    name: 'Avalanche C-Chain',
    chainId: 43114,
    shortName: 'ava',
    chain: 'AVA',
    networkId: 43114,
    rpc: ['https://avalanche.drpc.org', 'https://rpc.ankr.com/avalanche-c'],
    icon: require('../../assets/chain/avax.png'),
  },
  {
    name: 'Aurora',
    chainId: 1313161554,
    shortName: 'aurora',
    chain: 'AURORA',
    networkId: 1313161554,
    rpc: ['https://mainnet.aurora.dev'],
    icon: require('../../assets/chain/aurora.png'),
  },
  {
    name: 'Binance Smart Chain',
    chainId: 56,
    shortName: 'bsc',
    chain: 'BNB',
    networkId: 56,
    rpc: [
      'https://bsc-dataseed1.binance.org',
      'https://bsc-dataseed2.binance.org',
      'https://bsc-dataseed3.binance.org',
      'https://bsc-dataseed4.binance.org',
      'https://bsc-dataseed4.binance.org',
    ],
    icon: require('../../assets/chain/bsc.png'),
  },
  {
    name: 'Base',
    chainId: 8453,
    shortName: 'base',
    chain: 'BASE',
    networkId: 8453,
    rpc: ['https://mainnet.base.org'],
    icon: require('../../assets/chain/base.png'),
  },
  {
    name: 'Evmos',
    chainId: 9001,
    shortName: 'evmos',
    chain: 'EVMOS',
    networkId: 9001,
    rpc: ['https://evmos-evm.publicnode.com'],
    icon: require('../../assets/chain/evmos.png'),
  },
  {
    name: 'Fantom',
    chainId: 250,
    shortName: 'ftm',
    chain: 'FTM',
    networkId: 250,
    rpc: [
      'https://rpc.ankr.com/fantom/',
      'https://rpcapi.fantom.network/',
      'https://fantom-mainnet.public.blastapi.io/',
      'https://rpc.ftm.tools',
      'https://fantom-rpc.gateway.pokt.network',
      'https://1rpc.io/ftm',
      'https://fantom.publicnode.com',
      'https://fantom.blockpi.network/v1/rpc/public',
      'https://fantom.drpc.org/',
      'https://rpc.fantom.gateway.fm',
      'https://endpoints.omniatech.io/v1/fantom/mainnet/public',
      'https://fantom.api.onfinality.io/public',
      'https://fantom.rpc.thirdweb.com/',
    ],
    icon: require('../../assets/chain/ftm.png'),
  },
  {
    name: 'Moonbeam',
    chainId: 1284,
    shortName: 'moonbeam',
    chain: 'MOONBEAM',
    networkId: 1284,
    rpc: ['https://moonbeam.public-rpc.com'],
    icon: require('../../assets/chain/moonbeam.png'),
  },
  {
    name: 'Moonriver',
    chainId: 1285,
    shortName: 'moonriver',
    chain: 'MOONRIVER',
    networkId: 1285,
    rpc: ['https://moonriver.public.blastapi.io', 'https://moonriver.public.blastapi.io'],
    icon: require('../../assets/chain/moonriver.png'),
  },
  {
    name: 'Optimism',
    chain: 'ETH',
    rpc: [
      'https://mainnet.optimism.io',
      'https://optimism.publicnode.com',
      'wss://optimism.publicnode.com',
      'https://optimism.gateway.tenderly.co',
      'wss://optimism.gateway.tenderly.co',
    ],
    shortName: 'oeth',
    chainId: 10,
    networkId: 10,
    icon: require('../../assets/chain/op.png'),
  },
  {
    name: 'Polygon',
    chain: 'Polygon',
    rpc: [
      'https://polygon-rpc.com/',
      'https://rpc-mainnet.matic.network',
      'https://matic-mainnet.chainstacklabs.com',
      'https://rpc-mainnet.maticvigil.com',
      'https://rpc-mainnet.matic.quiknode.pro',
      'https://matic-mainnet-full-rpc.bwarelabs.com',
      'https://polygon-bor.publicnode.com',
      'wss://polygon-bor.publicnode.com',
      'https://polygon.gateway.tenderly.co',
      'wss://polygon.gateway.tenderly.co',
    ],
    shortName: 'matic',
    chainId: 137,
    networkId: 137,
    icon: require('../../assets/chain/matic.png'),
  },
];
