import { Chain } from 'packages/types';

export type TokenInfo = {
  chain: Chain;
  symbol: string;
  isToken: boolean;
  tokenType?: string;
  decimals: number;
  contractAddress?: string;
  displayDecimals: number;
  icon: any;
  price?: string;
  usd24hChange?: string;
  balance?: string;
  ids: string;
};

export const tokenList: TokenInfo[] = [
  {
    chain: Chain.ETH,
    symbol: 'ETH',
    isToken: false,
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/eth.png'),
    ids: 'ethereum',
  },
  {
    chain: Chain.ETH,
    symbol: 'USDT',
    isToken: true,
    contractAddress: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    decimals: 6,
    displayDecimals: 4,
    icon: require('../../assets/coin/usdt.png'),
    ids: 'tether',
  },
  {
    chain: Chain.ETH,
    symbol: 'USDC',
    isToken: true,
    contractAddress: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    decimals: 6,
    displayDecimals: 4,
    icon: require('../../assets/coin/usdc.png'),
    ids: 'usd-coin',
  },
  {
    chain: Chain.ETH,
    symbol: 'DAI',
    isToken: true,
    contractAddress: '0x6b175474e89094c44da98b954eedeac495271d0f',
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/dai.png'),
    ids: 'dai',
  },
  {
    chain: Chain.ETH,
    symbol: 'WBTC',
    isToken: true,
    contractAddress: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    decimals: 8,
    displayDecimals: 8,
    icon: require('../../assets/coin/wbtc.png'),
    ids: 'wrapped-bitcoin',
  },
  {
    chain: Chain.ETH,
    symbol: 'WETH',
    isToken: true,
    contractAddress: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/weth.png'),
    ids: 'weth',
  },
  {
    chain: Chain.ETH,
    symbol: 'UNI',
    isToken: true,
    contractAddress: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/uni.png'),
    ids: 'uniswap',
  },
  {
    chain: Chain.ETH,
    symbol: 'ARB',
    isToken: true,
    contractAddress: '0xB50721BCf8d664c30412Cfbc6cf7a15145234ad1',
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/arb.png'),
    ids: 'arbitrum',
  },
  {
    chain: Chain.ETH,
    symbol: 'LINK',
    isToken: true,
    contractAddress: '0x514910771AF9Ca656af840dff83E8264EcF986CA',
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/link.png'),
    ids: 'chainlink',
  },
  {
    chain: Chain.ETH,
    symbol: 'TRX',
    isToken: true,
    contractAddress: '0x50327c6c5a14DCaDE707ABad2E27eB517df87AB5',
    decimals: 6,
    displayDecimals: 4,
    icon: require('../../assets/coin/trx.png'),
    ids: 'tron',
  },
  {
    chain: Chain.ETH,
    symbol: 'BNB',
    isToken: true,
    contractAddress: '0xB8c77482e45F1F44dE1745F52C74426C631bDD52',
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/bnb.png'),
    ids: 'binancecoin',
  },
  {
    chain: Chain.ETH,
    symbol: 'CRO',
    isToken: true,
    contractAddress: '0xA0b73E1Ff0B80914AB6fe0444E65848C4C34450b',
    decimals: 8,
    displayDecimals: 4,
    icon: require('../../assets/coin/cro.png'),
    ids: 'crypto-com-chain',
  },
  {
    chain: Chain.ETH,
    symbol: 'SAND',
    isToken: true,
    contractAddress: '0x3845badAde8e6dFF049820680d1F14bD3903a5d0',
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/sand.png'),
    ids: 'the-sandbox',
  },
  {
    chain: Chain.ETH,
    symbol: 'SHIB',
    isToken: true,
    contractAddress: '0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE',
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/shib.png'),
    ids: 'shiba-inu',
  },
  {
    chain: Chain.ETH,
    symbol: 'MATIC',
    isToken: true,
    contractAddress: '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0',
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/matic.png'),
    ids: 'matic-network',
  },
  {
    chain: Chain.BTC,
    symbol: 'BTC',
    isToken: false,
    decimals: 8,
    displayDecimals: 8,
    icon: require('../../assets/coin/btc.png'),
    ids: 'bitcoin',
  },
  {
    chain: Chain.TRON,
    symbol: 'TRX',
    isToken: false,
    decimals: 6,
    displayDecimals: 6,
    icon: require('../../assets/coin/trx.png'),
    ids: 'tron',
  },
  {
    chain: Chain.TRON,
    symbol: 'USDT',
    isToken: true,
    decimals: 6,
    displayDecimals: 4,
    icon: require('../../assets/coin/usdt.png'),
    ids: 'tether',
  },
  {
    chain: Chain.TRON,
    symbol: 'USDC',
    isToken: true,
    decimals: 6,
    displayDecimals: 4,
    icon: require('../../assets/coin/usdc.png'),
    ids: 'usd-coin',
  },
  {
    chain: Chain.BSC,
    symbol: 'BNB',
    isToken: false,
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/bnb.png'),
    ids: 'binancecoin',
  },
  {
    chain: Chain.BSC,
    symbol: 'USDT',
    isToken: true,
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/usdt.png'),
    ids: 'tether',
  },
  {
    chain: Chain.BSC,
    symbol: 'BUSD',
    isToken: true,
    decimals: 18,
    displayDecimals: 8,
    icon: require('../../assets/coin/busd.png'),
    ids: 'binance-usd',
  },
  {
    chain: Chain.LTC,
    symbol: 'LTC',
    isToken: false,
    decimals: 8,
    displayDecimals: 8,
    icon: require('../../assets/coin/ltc.png'),
    ids: 'litecoin',
  },
];
